using System;
using System.Collections.Generic;
using System.Text;

namespace Tabula
{
    public class Generator
    {
        public CST.Scenario Scenario { get; set; }
        public StringBuilder Builder { get; set; }

        public void Generate(CST.Scenario scenario, string inputFilePath, StringBuilder builder)
        {
            Scenario = scenario;
            Builder = builder;

            BuildHeader(inputFilePath);
            OpenNamespace();
            OpenClass(inputFilePath);
            BuildBody();
            CloseClass();
            CloseNamespace();
        }

        public void BuildHeader(string inputFilePath)
        {
            Builder.AppendLine("//  This file was generated by TabulaClassGenerator version 0.1.");
            Builder.AppendLine($"//  To change this file, change the Tabula scenario at {inputFilePath}.");
            Builder.AppendLine("//  Currently only generates this rudimentary paste.  You have been warned.");
            Builder.AppendLine("using System;");
            Builder.AppendLine("using System.Collections.Generic;");
            Builder.AppendLine("using Acadis.Constants.Accounting;");
            Builder.AppendLine("using Acadis.Constants.Admin;");
            Builder.AppendLine("using Acadis.SystemUtilities;");
            Builder.AppendLine();
        }

        public void OpenNamespace()
        {
            Builder.AppendLine("namespace Tabula");
            Builder.AppendLine("{");
        }


        public void OpenClass(string inputFilePath)
        {
            //  remove everything before the last backslash
            int lastBackslash = inputFilePath.LastIndexOf("\\");
            if (lastBackslash != -1)
                inputFilePath = inputFilePath.Substring(lastBackslash + 1);

            //  remove everything after the last dot
            int lastDot = inputFilePath.LastIndexOf('.');
            if (lastDot != -1)
                inputFilePath = inputFilePath.Remove(lastDot);

            var className = inputFilePath.Replace(' ', '_').Replace('.', '_');
            Builder.AppendLine($"    public class {className}_generated  //  {Scenario.Label}");
            Builder.AppendLine("        : GeneratedScenarioBase, IGeneratedScenario");
            Builder.AppendLine("    {");
        }

        public void BuildBody()
        {
        }

        public List<string> GetNeededWorkflows()
        {
            var nws = new List<string>();

            //??? the moving hand writes...
            //Scenario.

            return nws;
        }

        //public void AddWorkflow(string workflowName)
        //{
        //    NeededWorkflows.Add(workflowName);
        //}

        public void BuildDeclarations()
        {
            foreach (var workflow in GetNeededWorkflows())
            {
                var varName = nameOfWorkflowInstance(workflow);
                Builder.AppendFormat("public {0} {1};{2}", workflow, varName, Environment.NewLine);
            }
        }

        public void BuildConstructor(List<string> neededImplementors)
        {

        }

        public void CloseClass()
        {
            Builder.AppendLine("    }");
        }

        public void CloseNamespace()
        {
            Builder.AppendLine("}");
        }

        public string nameOfWorkflowInstance(string workflowName)
        {
            var lastDot = workflowName.LastIndexOf('.');
            return workflowName.Substring(lastDot + 1).Replace("Workflow", "");
        }
    }
}
