//  This file was generated by TabulaClassGenerator version 0.4.
//  To change this file, change the Tabula scenario at K:\code\Tabula\studio_plugin_tester\ClassLibrary1\Scenarios\SeriousBusiness\UserCanGetSerious.tab.
//  Version 0.4 is not yet alpha (known missing 1.0 features).  You have been warned.
using System;
using System.Collections.Generic;
using Acadis.Constants.Accounting;
using Acadis.Constants.Admin;
using Acadis.SystemUtilities;
using Tabula.API;

namespace Tabula
{
    //  "We are arranging a Serious Conference"
    public class UserCanGetSerious_generated
        : GeneratedScenarioBase, IGeneratedScenario
    {
        public void ExecuteScenario()
        {
            paragraph__005_to_008();
            paragraph__011_to_012();
            Foreach_Row_in( table__017_to_018, paragraph__015_to_016 );
        }

        public void paragraph__005_to_008()
        {
            Label(     "Several serious topics are recommended");
            Do(() =>    Serious.Register__as_serious($"Saving for your retirement"), @"K:\code\Tabula\studio_plugin_tester\ClassLibrary1\Scenarios\SeriousBusiness\UserCanGetSerious.tab:6", @"Serious.Register__as_serious($""Saving for your retirement"")");
            Do(() =>    Serious.Register__as_serious($"Maintaining and improving your health"), @"K:\code\Tabula\studio_plugin_tester\ClassLibrary1\Scenarios\SeriousBusiness\UserCanGetSerious.tab:7", @"Serious.Register__as_serious($""Maintaining and improving your health"")");
            Do(() =>    Serious.Register__as_serious($"Bobcat Goldthwait"), @"K:\code\Tabula\studio_plugin_tester\ClassLibrary1\Scenarios\SeriousBusiness\UserCanGetSerious.tab:8", @"Serious.Register__as_serious($""Bobcat Goldthwait"")");
        }

        public void paragraph__011_to_012()
        {
            Label(     "On later review, some of these don't meet our standards");
            Unfound(  @"Remove ""Bobcat Goldthwait"" from our topics", @"K:\code\Tabula\studio_plugin_tester\ClassLibrary1\Scenarios\SeriousBusiness\UserCanGetSerious.tab:12");
        }

        public void paragraph__015_to_016()
        {
            Label(     "Check that our topics are shaping up extremely seriously");
            Do(() =>    Serious.Verify_that__is_serious(Var["topic"]), @"K:\code\Tabula\studio_plugin_tester\ClassLibrary1\Scenarios\SeriousBusiness\UserCanGetSerious.tab:16", @"Serious.Verify_that__is_serious(Var[""topic""])");
        }

        public Table table__017_to_018()
        {
            return new Table {
                Header = new List<string>     { "topic" },
                Data = new List<List<string>> {
                    new List<string>          { "Saving for your retirement" },
                }
            };
        };


        public LibContainingScenarios.Implementations.SeriousWorkflow Serious;

        public UserCanGetSerious_generated()
            : base()
        {
            Serious = new LibContainingScenarios.Implementations.SeriousWorkflow();
        }
    }
}
